### PR TITLE
Get python exec path using getExecutionDetails

### LINKED ISSUE #73: Python: Xray fails with "Please install a virtual environment" with venv activated
After connecting to my Xray instance successfully and initiating a scan I get an error that claims I don't have a virtual environment installed. Full error is:

```bash
Please install and activate a virtual environment before running Xray scan. Then, install your Python project in that environment.
```

My virtual environment is named 'venv' and lives at the root of my project. I have it selected as my virtual environment per VSCode's instructions and have pip installed all packages to that environment. Debug log from JFrog as follows:

```bash
[INFO - 3:56:52 PM] Starting slow scan
[INFO - 3:56:52 PM] Locating go.mod files in workspace "workspace".
[DEBUG - 3:56:53 PM] No go.mod files found in workspaces.
[INFO - 3:56:53 PM] Locating package json files in workspace "workspace".
[DEBUG - 3:56:53 PM] No package.json files found in workspaces.
[INFO - 3:56:53 PM] Locating python files in workspace "workspace".
[DEBUG - 3:56:53 PM] Detected python files in workspace workspace: [file:///project/directory/requirements.txt]
[INFO - 3:56:53 PM] Locating pom.xml files in workspace "workspace".
[DEBUG - 3:56:53 PM] No pom.xml files found in workspaces.
[INFO - 3:56:53 PM] Locating *.sln files in workspace "workspace".
[DEBUG - 3:56:53 PM] No *.sln files found in workspaces.
```

I thought I followed the instructions in the README correctly. Any thoughts on why this might be happening?

### PR DESCRIPTION
**Pull request by yahavi**
- [x] All [tests](https://github.com/jfrog/jfrog-vscode-extension#building-and-testing-the-sources) passed. If this feature is not already covered by the tests, I added new tests.
- [x] I used `npm run format` for formatting the code before submitting the pull request.
-----

May fix #73

* The `pythonPath` setting is deprecated. That means that the python executable details can no longer be retrieved from this setting - https://devblogs.microsoft.com/python/python-in-visual-studio-code-july-2021-release/#selecting-a-python-interpreter-no-longer-modifies-workspace-settings. Instead of using it, use [getExecutionDetails](https://github.com/microsoft/vscode-python/blob/main/src/client/api.ts#L67) API.
* In some cases the Python extension is already active and we try to activate it again. This returns an error, therefore we should check before activating it.

### CODE REVIEW

File: src/main/utils/pypiUtils.ts [hunk 1]
```diff
@@ -126,25 +126,30 @@ export class PypiUtils {
     }
 
     /**
-     * Return true iff VS-Code Python extension is installed.
+     * Return reference to the VS-Code Python extension if installed.
      * Activate it to allow tracking on environmental changes -
      *   If virtual env is not installed, we want that the Python extension will detect new virtualenv environments and suggest activation.
```
Comment (eyalbe4) [inline src/main/utils/pypiUtils.ts:131]: Redundant white-spaces before "If".

**Review by eyalbe4 — CHANGES_REQUESTED** [review]
