### PR TITLE
Filter out unused dependencies in Go

### LINKED ISSUE #109: Extension host terminated unexpectedly for Golang project
**Describe the bug**
Opening a Golang project in Visual Code with jFrog extension enabled causes notification message of "_Extension host terminated unexpectedly_".
Restarting the Extension Host makes no difference.
Opening Developer Tools and looking at the console there are the following messages:
```
 WARN UNRESPONSIVE extension host, 'JFrog.jfrog-vscode-extension' took 95% of 5622.04ms, saved PROFILE here: 'file:///c%3A/Users/{username}/AppData/Local/Temp/exthost-482aef.cpuprofile'

Array(2)
0: id: "gc", percentage: 5, total: 295823
1: id: "JFrog.jfrog-vscode-extension", percentage: 95, total: 5325888
```
and
```
<--- Last few GCs --->
[20552:0000028200000000]    98829 ms: Scavenge (reduce) 3617.3 (3949.9) -> 3616.7 (3949.9) MB, 4.9 / 0.0 ms  (average mu = 0.803, current mu = 0.599) allocation failure
[20552:0000028200000000]    99409 ms: Scavenge (reduce) 3617.4 (3949.9) -> 3616.8 (3949.9) MB, 8.2 / 0.0 ms  (average mu = 0.803, current mu = 0.599) allocation failure
<--- JS stacktrace --->
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
<--- Last few GCs --->
[20552:0000028200000000]    98829 ms: Scavenge (reduce) 3617.3 (3949.9) -> 3616.7 (3949.9) MB, 4.9 / 0.0 ms  (average mu = 0.803, current mu = 0.599) allocation failure
[20552:0000028200000000]    99409 ms: Scavenge (reduce) 3617.4 (3949.9) -> 3616.8 (3949.9) MB, 8.2 / 0.0 ms  (average mu = 0.803, current mu = 0.599) allocation failure
<--- JS stacktrace --->
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
```
and
```
ERR Extension host terminated unexpectedly. The following extensions were running:
vscode.microsoft-authentication, 
vscode.debug-auto-launch,
vscode.git,
JFrog.jfrog-vscode-extension,
golang.go,
ms-vscode.js-debug,
vscode.github,
vscode.github-authentication,
vscode.emmet, vscode.merge-conflict,
ms-vscode-remote.remote-wsl-recommender,
vscode.testing-editor-contributions,
dbaeumer.vscode-eslint,
eamodio.gitlens,
ms-vscode-remote.remote-wsl
```

**To Reproduce**
Open Golang project of ~188 .go files and ~27 third party imports referenced in the `go.mod`. The `go.sum` file is populated and valid.

**Expected behavior**

**Screenshots**

**Versions**
- JFrog VS-Code extension version: `1.8.0`
- JFrog VS-Code extension operating system: `Windows 10 21H1`
- JFrog Xray Version: `JFrog Cloud`
- VS-Code version: `1.58.2`
- Golang version: `1.16.6`

**Additional context**
The extension works fine with a very small Golang project of 5 files.
Running on i7 1.99GHz laptop with 40GB RAM

### PR DESCRIPTION
**Pull request by yahavi**
- [x] All [tests](https://github.com/jfrog/jfrog-vscode-extension#building-and-testing-the-sources) passed. If this feature is not already covered by the tests, I added new tests.
- [x] I used `npm run format` for formatting the code before submitting the pull request.
-----

Resolves #109

Filter out unused dependencies in Go by intersecting `go mod graph` results with `go list -m all` results.
The results of `go list -m all` should show only dependencies that are actually in use in the project.
Read more about this issue here: https://github.com/jfrog/jfrog-vscode-extension/issues/109#issuecomment-903277188

### CODE REVIEW

**Review by eyalbe4 — CHANGES_REQUESTED** [review]
@yahavi - as for the usage of ```go list -m all```, will you be able to sync with @sverdlov93?
Michael may have found a way of making the result of  ```go list -m all``` more precise, by setting the output format.

File: src/main/treeDataProviders/dependenciesTree/dependenciesRoot/goTree.ts [hunk 1]
```diff
@@ -40,52 +37,88 @@ export class GoTreeNode extends RootNode {
...
 
-    private buildDependenciesMapAndDirectDeps(goList: string[]) {
-        let i: number = 0;
+    /**
+     * Run "go mod graph" in order to create the dependency tree later on.
+     * @returns a list of dependencies in the following order:
+     * For a given index i, if i is even (i%2==0) results[i] is the package that depends on results[i+1]: results[i] -> results[i+1].
+     * The first lines of the even indices contain no versions. Those are the direct dependencies.
+     */
+    private runGoModGraph(): string[] {
```
Comment (eyalbe4) [inline src/main/treeDataProviders/dependenciesTree/dependenciesRoot/goTree.ts:53]: Instead of using a less-trial output structure for this function, I recommend we use a class with two fields, with self-explanatory names, instead of the even / uneven array structure.

**Review by eyalbe4 — CHANGES_REQUESTED** [review]
Let's update the ```Go Projects``` section in the README following these changes.
